var source = {
	main: [
		{ id: "START", type: "INFO", status: "AVAL", name: "Inicio", fixed: true, fx: document.body.offsetWidth/2, fy: document.body.offsetHeight/2  },
		{ id: "R01",   type: "TASK", status: "LOCK", name: "Inscripción", 	depends: [ "START" ] },
		{ id: "R02",   type: "TASK", status: "LOCK", name: "Re-inscripción",	depends: [ "J01"   ] },
		{ id: "R03",   type: "TASK", status: "LOCK", name: "Re-inscripción",	depends: [ "J02"   ] },
		{ id: "R04",   type: "TASK", status: "LOCK", name: "Re-inscripción",	depends: [ "J03"   ] },
		{ id: "R05",   type: "TASK", status: "LOCK", name: "Re-inscripción",	depends: [ "J04"   ] },
		{ id: "R06",   type: "TASK", status: "LOCK", name: "Re-inscripción",	depends: [ "J05"   ] },
		{ id: "R07",   type: "TASK", status: "LOCK", name: "Re-inscripción",	depends: [ "J06"   ] },
		{ id: "R08",   type: "TASK", status: "LOCK", name: "Re-inscripción",	depends: [ "J07"   ] },
		{ id: "J01", name: "1° semestre", type: "JOINER", status: "LOCK", morethan: [ 2 ],
			depends: [
				"C101",
				"C102",
				"C103",
				"C104",
				"C105",
			],
		},
		{ id: "J02", name: "2° semestre", type: "JOINER", status: "LOCK", morethan: [ 3 ],
			depends: [
				"C201",
				"C202",
				"C203",
				"C204",
				"C205",
				"C206",
			],
		},
		{ id: "J03", name: "3° semestre", type: "JOINER", status: "LOCK", morethan: [ 3 ],
			depends: [
				"C301",
				"C302",
				"C303",
				"C304",
				"C305",
				"C306",
				"C307",
			],
		},
		{ id: "J04", name: "4° semestre", type: "JOINER", status: "LOCK", morethan: [ 3 ],
			depends: [
				"C401",
				"C402",
				"C403",
				"C404",
				"C405",
				"C406",
				"C407",
			],
		},
		{ id: "J05", name: "5° semestre", type: "JOINER", status: "LOCK", morethan: [ 3 ],
			depends: [
				"C501",
				"C502",
				"C503",
				"C504",
				"C505",
				"C506",
				"C507",
			],
		},
		{ id: "J06", name: "6° semestre", type: "JOINER", status: "LOCK", morethan: [ 3 ],
			depends: [
				"C601",
				"C602",
				"C603",
				"O001",
				"O002",
				"C618",
				"C619",
			],
		},
		{ id: "J07", name: "7° semestre", type: "JOINER", status: "LOCK", morethan: [ 3 ],
			depends: [
				"C701",
				"C702",
				"O003",
				"O004",
				"C717",
				"C718",
			],
		},
		{ id: "J08", name: "8° semestre", type: "JOINER", status: "LOCK", morethan: [ 3 ],
			depends: [
				"C801",
				"C802",
				"C803",
				"C804",
				"C805",
			],
		},
{ id: "C101", depends: [ "R01"                 ], type: "MISSION", status: "LOCK", period: 1,	name: "FUNDAMENTOS DE PROGRAMACION					", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C102", depends: [ "R01"                 ], type: "MISSION", status: "LOCK", period: 1,	name: "MATEMATICAS DISCRETAS						", need: "OBLIGATORIA",	credits: 10.50	},
{ id: "C103", depends: [ "R01"                 ], type: "MISSION", status: "LOCK", period: 1,	name: "CALCULO								", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C104", depends: [ "R01"                 ], type: "MISSION", status: "LOCK", period: 1,	name: "ANALISIS VECTORIAL						", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C105", depends: [ "R01"                 ], type: "MISSION", status: "LOCK", period: 1,	name: "COMUNICACION ORAL Y ESCRITA					", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C201", depends: [ "R02", "C101"         ], type: "MISSION", status: "LOCK", period: 2,	name: "ALGORITMOS Y ESTRUCTURA DE DATOS					", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C202", depends: [ "R02"                 ], type: "MISSION", status: "LOCK", period: 2,	name: "ALGEBRA LINEAL							", need: "OBLIGATORIA",	credits: 9.00	},
{ id: "C203", depends: [ "R02", "C103"         ], type: "MISSION", status: "LOCK", period: 2,	name: "CALCULO APLICADO							", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C204", depends: [ "R02", "C104"         ], type: "MISSION", status: "LOCK", period: 2,	name: "MECANICA Y ELECTROMAGNETISMO					", need: "OBLIGATORIA",	credits: 10.50	},
{ id: "C205", depends: [ "R02"                 ], type: "MISSION", status: "LOCK", period: 2,	name: "INGENIERIA ETICA Y SOCIEDAD					", need: "OBLIGATORIA",	credits: 9.00	},
{ id: "C206", depends: [ "R02"                 ], type: "MISSION", status: "LOCK", period: 2,	name: "FUNDAMENTOS ECONOMICOS						", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C301", depends: [ "R03", "C201"         ], type: "MISSION", status: "LOCK", period: 3,	name: "ANALISIS Y DISEÑO DE ALGORITMOS					", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C302", depends: [ "R03", "C201"         ], type: "MISSION", status: "LOCK", period: 3,	name: "PARADIGMAS DE PROGRAMACION					", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C303", depends: [ "R03", "C203"         ], type: "MISSION", status: "LOCK", period: 3,	name: "ECUACIONES DIFERENCIALES						", need: "OBLIGATORIA",	credits: 9.00	},
{ id: "C304", depends: [ "R03", "C102"         ], type: "MISSION", status: "LOCK", period: 3,	name: "FUNDAMENTOS DE DISEÑO DIGITAL					", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C305", depends: [ "R03", "C204"         ], type: "MISSION", status: "LOCK", period: 3,	name: "CIRCUITOS ELECTRICOS						", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C306", depends: [ "R03", "C102"         ], type: "MISSION", status: "LOCK", period: 3,	name: "BASES DE DATOS							", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C307", depends: [ "R03", "C206"         ], type: "MISSION", status: "LOCK", period: 3,	name: "FINANZAS EMPRESARIALES						", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C401", depends: [ "R04", "C201"         ], type: "MISSION", status: "LOCK", period: 4,	name: "TEORIA DE LA COMPUTACION						", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C402", depends: [ "R04", "C203"         ], type: "MISSION", status: "LOCK", period: 4,	name: "PROBABILIDAD Y ESTADISTICA					", need: "OBLIGATORIA",	credits: 9.00	},
{ id: "C403", depends: [ "R04", "C303"         ], type: "MISSION", status: "LOCK", period: 4,	name: "MATEMATICAS AVANZADAS PARA LA INGENIERIA				", need: "OBLIGATORIA",	credits: 9.00	},
{ id: "C404", depends: [ "R04", "C304"         ], type: "MISSION", status: "LOCK", period: 4,	name: "DISEÑO DE SISTEMAS DIGITALES					", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C405", depends: [ "R04", "C305"         ], type: "MISSION", status: "LOCK", period: 4,	name: "ELECTRONICA ANALOGICA						", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C406", depends: [ "R04", "C306"         ], type: "MISSION", status: "LOCK", period: 4,	name: "TECNOLOGIAS PARA DESARROLLO DE APLICACIONES WEB			", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C407", depends: [ "R04", "C201"         ], type: "MISSION", status: "LOCK", period: 4,	name: "SISTEMAS OPERATIVOS						", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C501", depends: [ "R05", "C401"         ], type: "MISSION", status: "LOCK", period: 5,	name: "COMPILADORES							", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C502", depends: [ "R05", "C403"         ], type: "MISSION", status: "LOCK", period: 5,	name: "PROCESAMIENTO DIGITAL DE SEÑALES					", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C503", depends: [ "R05", "C404"         ], type: "MISSION", status: "LOCK", period: 5,	name: "ARQUITECTURA DE COMPUTADORAS					", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C504", depends: [ "R05", "C405"         ], type: "MISSION", status: "LOCK", period: 5,	name: "INSTRUMENTACION Y CONTROL					", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C505", depends: [ "R05", "C306"         ], type: "MISSION", status: "LOCK", period: 5,	name: "ANALISIS Y DISEÑO DE SISTEMAS					", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C506", depends: [ "R05", "C307"         ], type: "MISSION", status: "LOCK", period: 5,	name: "FORMULACION Y EVALUACION DE PROYECTOS INFORMATICOS		", need: "OBLIGATORIA",	credits: 6.00	},
{ id: "C507", depends: [ "R05"                 ], type: "MISSION", status: "LOCK", period: 5,	name: "REDES DE COMPUTADORAS						", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C601", depends: [ "R06"                 ], type: "MISSION", status: "LOCK", period: 6,	name: "INTELIGENCIA ARTIFICIAL						", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C602", depends: [ "R06", "C503", "C502" ], type: "MISSION", status: "LOCK", period: 6,	name: "SISTEMAS EN CHIP							", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C603", depends: [ "R06"                 ], type: "MISSION", status: "LOCK", period: 6,	name: "METODOS CUANTITATIVOS PARA LA TOMA DE DECISIONES			", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C604", depends: [ "R06"                 ], type: "MISSION", status: "LOCK", period: 6,	name: "BIG DATA|NON-RELATIONAL DATABASES				", need: "OPTATIVA   ", credits: 7.50	},
{ id: "C605", depends: [ "R06"                 ], type: "MISSION", status: "LOCK", period: 6,	name: "DES. DE APLIC|SOFTWARE QUALLITY ASSURANCE AND DESING PATTERNS	", need: "OPTATIVA   ", credits: 7.50	},
{ id: "C606", depends: [ "R06"                 ], type: "MISSION", status: "LOCK", period: 6,	name: "MINERIA DE DATOS|STATISTICAL TOOLS FOR DATA ANALYTICS		", need: "OPTATIVA   ", credits: 7.50	},
{ id: "C607", depends: [ "R06"                 ], type: "MISSION", status: "LOCK", period: 6,	name: "INSTRUMENTAL VIRTUAL|VIRTUAL INSTRUMENTATION			", need: "OPTATIVA   ", credits: 7.50	},
{ id: "C608", depends: [ "R06"                 ], type: "MISSION", status: "LOCK", period: 6,	name: "INTERNET DE LAS COSAS|EMBEDDED SYSTEMS				", need: "OPTATIVA   ", credits: 7.50	},
{ id: "C609", depends: [ "R06"                 ], type: "MISSION", status: "LOCK", period: 6,	name: "GOBIERNO DE TI|COMPUTER SECURITY					", need: "OPTATIVA   ", credits: 7.50	},
{ id: "C610", depends: [ "R06"                 ], type: "MISSION", status: "LOCK", period: 6,	name: "CRIPTOGRAFIA|INTRODUCTION TO CRYPTOGRAPHY			", need: "OPTATIVA   ", credits: 7.50	},
{ id: "C611", depends: [ "R06"                 ], type: "MISSION", status: "LOCK", period: 6,	name: "PROC. DE LENG. NAT|MACHINE LEARNING				", need: "OPTATIVA   ", credits: 7.50	},
{ id: "C612", depends: [ "R06"                 ], type: "MISSION", status: "LOCK", period: 6,	name: "ALGORITMOS BIOINSPIRADOS|GENETIC ALGORITHMS			", need: "OPTATIVA   ", credits: 7.50	},
{ id: "C613", depends: [ "R06"                 ], type: "MISSION", status: "LOCK", period: 6,	name: "COMPUTACION GRAFICA|COMPUTER GRAPHICS				", need: "OPTATIVA   ", credits: 7.50	},
{ id: "C614", depends: [ "R06"                 ], type: "MISSION", status: "LOCK", period: 6,	name: "VISION POR COMPUTADORA|MACHINE LEARNING				", need: "OPTATIVA   ", credits: 7.50	},
{ id: "C615", depends: [ "R06"                 ], type: "MISSION", status: "LOCK", period: 6,	name: "SISTEMAS COMPLEJOS|CELLULAR AUTOMATA				", need: "OPTATIVA   ", credits: 7.50	},
{ id: "C616", depends: [ "R06"                 ], type: "MISSION", status: "LOCK", period: 6,	name: "GES. DE EMP. DE ALTA TEC|HIGH TECHNOLOGY ENTERPRISE MANAGEMENT	", need: "OPTATIVA   ", credits: 7.50	},
{ id: "C617", depends: [ "R06"                 ], type: "MISSION", status: "LOCK", period: 6,	name: "TOPICOS SEL. DE COM|COMPUTIG SELECTED TOPICS I			", need: "OPTATIVA   ", credits: 7.50	},
{ id: "C618", depends: [ "R06", "C506", "C505" ], type: "MISSION", status: "LOCK", period: 6,	name: "INGENIERIA DE SOFTWARE						", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C619", depends: [ "R06", "C507"         ], type: "MISSION", status: "LOCK", period: 6,	name: "APLICACIONES PARA COMUNICACIONES EN RED				", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C701", depends: [ "R07", "TT01"         ], type: "MISSION", status: "LOCK", period: 7,	name: "TRABAJO TERMINAL I						", need: "OBLIGATORIA",	credits: 12.00	},
{ id: "C702", depends: [ "R07", "C619"         ], type: "MISSION", status: "LOCK", period: 7,	name: "SISTEMAS DISTRIBUIDOS						", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C703", depends: [ "R07"                 ], type: "MISSION", status: "LOCK", period: 7,	name: "BIG DATA|BIG DATA						", need: "OPTATIVA   ", credits: 7.50	},
{ id: "C704", depends: [ "R07"                 ], type: "MISSION", status: "LOCK", period: 7,	name: "DES. DE APLIC|WEB CLIENT AND BACKEND DEVELOPMEN FRAMEWORKS	", need: "OPTATIVA   ", credits: 7.50	},
{ id: "C705", depends: [ "R07"                 ], type: "MISSION", status: "LOCK", period: 7,	name: "MINERIA DE DATOS|DATA MINING					", need: "OPTATIVA   ", credits: 7.50	},
{ id: "C706", depends: [ "R07"                 ], type: "MISSION", status: "LOCK", period: 7,	name: "INSTRUMENTAL VIRTUAL|VIRTUAL INSTRUMENTIATION APPLICATIONS	", need: "OPTATIVA   ", credits: 7.50	},
{ id: "C707", depends: [ "R07"                 ], type: "MISSION", status: "LOCK", period: 7,	name: "INTERNET DE LAS COSAS|INTERNET OF THINGS				", need: "OPTATIVA   ", credits: 7.50	},
{ id: "C708", depends: [ "R07"                 ], type: "MISSION", status: "LOCK", period: 7,	name: "GOBIERNO DE TI|IT GOVERNANCE					", need: "OPTATIVA   ", credits: 7.50	},
{ id: "C709", depends: [ "R07"                 ], type: "MISSION", status: "LOCK", period: 7,	name: "CRIPTOGRAFIA|SELECTED TOPICS IN CRYPTOGRAPHY			", need: "OPTATIVA   ", credits: 7.50	},
{ id: "C710", depends: [ "R07"                 ], type: "MISSION", status: "LOCK", period: 7,	name: "PROC. DE LENG|NATURAL LANGUAGE PROCESSING			", need: "OPTATIVA   ", credits: 7.50	},
{ id: "C711", depends: [ "R07"                 ], type: "MISSION", status: "LOCK", period: 7,	name: "ALGORITMOS BIOINSPIRADOS|BIOINFORMATICS				", need: "OPTATIVA   ", credits: 7.50	},
{ id: "C712", depends: [ "R07"                 ], type: "MISSION", status: "LOCK", period: 7,	name: "COMPUTACION GRAFICA|VIRTUAL AND AUGMENTED REALITY		", need: "OPTATIVA   ", credits: 7.50	},
{ id: "C713", depends: [ "R07"                 ], type: "MISSION", status: "LOCK", period: 7,	name: "VISION POR COMPUTADORA|IMAGE ANALYSIS				", need: "OPTATIVA   ", credits: 7.50	},
{ id: "C714", depends: [ "R07"                 ], type: "MISSION", status: "LOCK", period: 7,	name: "SISTEMAS COMPLEJOS|COMPLEX SYSTEMS				", need: "OPTATIVA   ", credits: 7.50	},
{ id: "C715", depends: [ "R07"                 ], type: "MISSION", status: "LOCK", period: 7,	name: "GES. DE EMP. DE ALTA TEC|ECONOMIC ENGINEERING			", need: "OPTATIVA   ", credits: 7.50	},
{ id: "C716", depends: [ "R07"                 ], type: "MISSION", status: "LOCK", period: 7,	name: "TOPICOS SEL. DE COM|COMPUTTING SELECTED TOPICS II		", need: "OPTATIVA   ", credits: 7.50	},
{ id: "C717", depends: [ "R07"                 ], type: "MISSION", status: "LOCK", period: 7,	name: "DESARROLLO DE APLICACIONES MOVILES NATIVAS			", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C718", depends: [ "R07", "C619"         ], type: "MISSION", status: "LOCK", period: 7,	name: "ADMINISTRACION DE SERVICIOS EN RED				", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C801", depends: [ "R08", "C701"         ], type: "MISSION", status: "LOCK", period: 8,	name: "TRABAJO TERMINAL II						", need: "OBLIGATORIA",	credits: 12.00	},
{ id: "C802", depends: [ "R08"                 ], type: "MISSION", status: "LOCK", period: 8,	name: "LIDERAZGO PERSONAL						", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C803", depends: [ "R08"                 ], type: "MISSION", status: "LOCK", period: 8,	name: "GESTION EMPRESARIAL						", need: "OBLIGATORIA",	credits: 7.50	},
{ id: "C804", depends: [ "R08"                 ], type: "MISSION", status: "LOCK", period: 8,	name: "ESTANCIA PROFESIONAL						", need: "OBLIGATORIA",	credits: 3.00	},
{ id: "C805", depends: [ "R08"                 ], type: "MISSION", status: "LOCK", period: 8,	name: "DESARROLLO DE HABILIDADES SOCIALES PARA LA ALTA DIRECCION	", need: "OBLIGATORIA",	credits: 3.00	},

{ id: "TT00", depends: [ "R06"		       ], type: "TASK", status: "LOCK", name: "Busqueda del protocolo",
	description: "Encuentra un protocolo de trabajo terminal de tu conveniencia ya sea con profesores o revisa las propuestas de la <a href='https://drive.google.com/file/d/1yRdanycRWIcQDyuvRXf3Ccok_FVTr-Tn/view'>CATT</a>"
},
{ id: "TT01", depends: [ "TT00"		       ], type: "TASK", status: "LOCK", name: "Relización del protocolo",
	description: "Realiza tu protocolo y entregalo en el <a href='https://forms.gle/sbW3oZirBGeJQxuG8'>formulario de la CATT</a>"
},

{ id: "O001",  type: "JOINER",  status: "LOCK", period: 6,	name: "OPTATIVA A1							", morethan: 1, lessthan: 1,
	depends: [
		"C604",
		"C605",
		"C606",
		"C607",
		"C608",
		"C609",
		"C610",
		"C611",
		"C612",
		"C613",
		"C614",
		"C615",
		"C616",
		"C617",
	],	
},
{ id: "O002",  type: "JOINER",  status: "LOCK", period: 6,	name: "OPTATIVA B1							", morethan: 1, lessthan: 1,
	depends: [
		"C604",
		"C605",
		"C606",
		"C607",
		"C608",
		"C609",
		"C610",
		"C611",
		"C612",
		"C613",
		"C614",
		"C615",
		"C616",
		"C617",
	],	
},
{ id: "O003",  type: "JOINER",  status: "LOCK", period: 6,	name: "OPTATIVA A2							", morethan: 1, lessthan: 1,
	depends: [
		"R06",
		"C703",
		"C704",
		"C705",
		"C706",
		"C707",
		"C708",
		"C709",
		"C710",
		"C711",
		"C712",
		"C713",
		"C714",
		"C715",
		"C716",
	],	
},
{ id: "O004",  type: "JOINER",  status: "LOCK", period: 6,	name: "OPTATIVA B2							", morethan: 1, lessthan: 1,
	depends: [
		"R06",
		"C703",
		"C704",
		"C705",
		"C706",
		"C707",
		"C708",
		"C709",
		"C710",
		"C711",
		"C712",
		"C713",
		"C714",
		"C715",
		"C716",
	],	
},
	{ id: "SS01", name: "Sericio social", type: "INFO", depends: [ "J05" ] },
	{ id: "SS02", name: "SISS Busca servicio", type: "TASK", depends: [ "SS01" ],
		description: "Revisa y busca un prestatario de tu conveniencia en el <a href='https://serviciosocial.ipn.mx/infoServSoc/InfoServSocListaPrsttrPerf.do?cvePerfil=36'>SISS Prestatarios</a>"
	},
	{ id: "SS03", name: "SISS fechas", type: "TASK", depends: [ "SS01" ],
		description: "Consulta las fechas autorizadas por la <a href='https://serviciosocial.ipn.mx/documentos/VerCalendario.do'>DEySS</a>"
	},
	{ id: "SS04", name: "SISS acuerdos", type: "TASK", depends: [ "SS02" ],
		description: "Llega a un acuerdo con un prestatario"
	},
	{ id: "SS05", name: "SISS Pre-registro", type: "TASK", depends: [ "SS04" ],
		description: "Realiza tu preregistro en el SISS <a href='https://serviciosocial.ipn.mx/accion/AceptaPrerregistroPrestadorSS.do'>SISS</a> con tu correo institucional."
	},
	{ id: "SS06", name: "SISS Contancia de creditos", type: "TASK", depends: [ "SS01" ],
		description: "Solicita la constancia de creditos en el formulario <a href='https://forms.office.com/r/7dXtF7j1Fb'>formulario</a>"
	},
	{ id: "SS07", name: "SS ESCOM Validación", type: "TASK", depends: [ "SS03", "SS05", "SS06" ],
		description: "Envia un correro al <a href='mailito:servicio_social_escom@ipn.mx?subject=\"Validación de pre-registro a {PRESENCIAL FUERA DE ESCOM, A DISTANCIA EN ESCOM, DISTANCIA, PRESENCIAL EN ESCOM}\"&body=\"Nomre completo\nBoleta\nConsntancia de créditos para serivcio social vigente\nVigencia de derechos del IMSS, ISSTE si eres estudiante\"'> departamento de sericio social de ESCOM</a> con el asunto \"Validación de pre-registro a {PRESENCIAL FUERA DE ESCOM, A DISTANCIA EN ESCOM, DISTANCIA, PRESENCIAL EN ESCOM}\" y con tu nombre, bolete, contancia de créditos y vigdencia de derechos IMSS/ISSTE."
	},
	{ id: "SS08", name: "SISS Alta", type: "TASK", depends: [ "SS07" ],
		description: "Solicita con tu prestatario tu alta en el SISS"
	},
	{ id: "SS09", name: "SISS Carta compromiso", type: "TASK", depends: [ "SS08" ],
		description: "Ingresa al <a href='https://serviciosocial.ipn.mx'>SISS</a> y descarga tu carta compromiso"
	},
	{ id: "SS10", name: "SS ESCOM 2da Validación", type: "TASK", depends: [ "SS06", "SS09" ],
		description: "Sube tu carta compromiso, CURP, y contancia de créditos al <a href='https://tinyurl.com/y6o4xdyx'>formulario</a>"
	},
	{ id: "SS11", name: "SS ESCOM 3ra Validación", type: "TASK", depends: [ "SS10" ],
		description: "Pide el visto bueno al <a href='mailito:servicio_social_escom@ipn.mx'>departamento de servicio social de ESCOM</a> antes de la fecha del <a href='https://serviciosocial.ipn.mx/documentos/VerCalendario.do'>DEySS</a> antes de las 5:00 p.m."
	},
	{ id: "SS12", name: "SS ESCOM 4da Validación", type: "TASK", depends: [ "SS06", "SS09", "SS11" ],
		description: "Recive los formatos de reporte mensual a tu correo"
	},
	{ id: "SS13", name: "Reporte 1° mes", type: "MISSION", depends: [ "SS12" ], },
	{ id: "SS14", name: "Reporte 2° mes", type: "MISSION", depends: [ "SS13" ], },
	{ id: "SS15", name: "Reporte 3° mes", type: "MISSION", depends: [ "SS14" ], },
	{ id: "SS16", name: "Reporte 4° mes", type: "MISSION", depends: [ "SS15" ], },
	{ id: "SS17", name: "Reporte 5° mes", type: "MISSION", depends: [ "SS16" ], },
	{ id: "SS18", name: "Reporte 6° mes", type: "MISSION", depends: [ "SS17" ], },
	{ id: "BC00", name: "SIBEC Bases", type: "TASK", depends: [ "R01" ],
		description: "Revisa las bases en SIBEC"
	},
	]
};
